# Development environment
development:
  platform:
    cloud:
      sut:
        host:
        username:
        password:
  application:
    container:
      sut:
        host:
        username:
        password:
  network_and_storage:
    cinder:
      sut:
        host:
        username:
        password:
    neutron:
      sut:
        host:
        username:
        password:
    sahara:
      sut:
        host:
        username:
        password:
    manila:
      sut:
        host:
        username:
        password:
    management:
      sut:
        host:
        username:
        password:
  common:
    portal:
      uri:
    cwe:
      uri: 
      id:
      sso_username:
      sso_password: 
    caas:
      uri:
      id:
    rhcert:
      ip:
      sso_username: 
      sso_password: 
      username:
      password:
    logpath: 

# QA environment
qa:
  platform:
    cloud:
      sut:
        host:
        username:
        password:
  application:
    container:
      sut:
        host:
        username:
        password:
  network_and_storage:
    cinder:
      sut:
        host:
        username:
        password:
    neutron:
      sut:
        host:
        username:
        password:
    sahara:
      sut:
        host:
        username:
        password:
    manila:
      sut:
        host:
        username:
        password:
    management:
      sut:
        host:
        username:
        password:
  common:
    portal:
      uri:
    cwe:
      url: <fake_url>
      id:
      sso_username: <fake_username>
      sso_password: <fake_passw>
    caas:
      uri:
      id:
    rhcert:
      ip: <fake>
      sso_username: <fake>
      sso_password: <fake>
      username:
      password:

# Stage environment
stage:
  platform:
    cloud:
      sut:
        host:
        username:
        password:
  application:
    container:
      sut:
        host:
        username:
        password:
  network_and_storage:
    cinder:
      sut:
        host:
        username:
        password:
    neutron:
      sut:
        host:
        username:
        password:
    sahara:
      sut:
        host:
        username:
        password:
    manila:
      sut:
        host:
        username:
        password:
    management:
      sut:
        host:
        username:
        password:
  common:
    portal:
      uri:
    cwe:
      uri:
      id:
      sso_username:
      sso_password:
    caas:
      uri:
      id:
    rhcert:
      ip: 
      sso_username: 
      sso_password: 
      username:
      password:
parents:
    cinder: 
    neutron: 
    sahara: 
    manila: 
    cloud: 
    management: 
    container: 
